spring.application.name=auth-service

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5001/auth_db
spring.datasource.username=auth_service
spring.datasource.password=onelight_dev_password
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# Server
# ===============================
server.port=4001


# ===============================
# gRPC - User Service
# ===============================
grpc.user-service.host=localhost
grpc.user-service.port=9092


# ===============================
# JWT
# ===============================
security.jwt.secret=BPVi0OhixBxpg/TGQKQflOtq1fxNYkTzIZk69qfRykw=
security.jwt.expiration-ms=900000


# ===============================
# Logging
# ===============================
logging.level.root=info