spring.application.name=message-service

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9095}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false

server.port=${SERVER_PORT:4004}

grpc.circle-service.host=${GRPC_CIRCLE_SERVICE_HOST:localhost}
grpc.circle-service.port=${GRPC_CIRCLE_SERVICE_PORT:9093}

logging.level.root=info

management.endpoints.web.exposure.include=health,info
