GET http://localhost:8080/api/v1/users/18ab8cf5-77e0-4caa-9850-6dae493f78a7
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxOGFiOGNmNS03N2UwLTRjYWEtOTg1MC02ZGFlNDkzZjc4YTciLCJlbWFpbCI6InRodXNpdGhhQGV4YW1wbGUuY29tIiwiaWF0IjoxNzkxMjYwNzQ0LCJleHAiOjE3OTEyNjE2NDR9.3Se5pNX5-jhed6RLtOxHXIUlCO9Ratrd2J3QbgpA3jY