POST http://localhost:8080/api/v1/auth/validate
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxOGFiOGNmNS03N2UwLTRjYWEtOTg1MC02ZGFlNDkzZjc4YTciLCJlbWFpbCI6InRodXNpdGhhQGV4YW1wbGUuY29tIiwiaWF0IjoxNzkxMjYxMDczLCJleHAiOjE3OTEyNjE5NzN9.OZaLDUXUYOz5v_EoVnaNHE95NWjByRHUr4OUNivxz0Y